name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: macOS-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-name: pyaccel-test
        create-args: >-
          python=${{matrix.python-version}}
          numpy
          scipy
          cython
          discretize
          meson-python
          meson
          ninja
          pytest
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Install package
      run: >-
        ./install_editable.sh
      shell: micromamba-shell {0}

    - name: run test
      run: pytest tests/test_pyaccel.py
      shell: micromamba-shell {0}

